name: pages-deploy

on:
  push:
    branches:
      - main
      - temp-deploy-fix  # allow deploys from temp branch too

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Example step - adjust based on your actual build
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v2

